### PR TITLE
Revert "Update matchms to 0.22.0"

### PR DESCRIPTION
**Pull request by hechth**
Reverts RECETOX/galaxytools#395

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Just noticed that the TS seems to contain only version 0.17. 

Is the deploy failure notification running on this repo: https://github.com/bernt-matthias/recetox-galaxytools/blob/7bc1710e91d5b1f07326c4eb3b96d4162be4e87d/.github/workflows/pr.yaml#L419?

**Comment by hechth** [comment]
@bernt-matthias yeah we seem to have some issues on the CI in general with deploying the tools to the toolshed and collecting the test results - I'm a bit puzzled at the moment.

**Comment by bgruening** [comment]
Is it in sync with the IUC GitHub actions?

**Comment by bernt-matthias** [comment]
Seems so. If Pat is defined the bot should respond if deployment failed https://github.com/RECETOX/galaxytools/blob/6ea2a2ce53ad2cd15ada661d0bffb9d570c04389/.github/workflows/pr.yaml#L435

**Comment by hechth** [comment]
The slash CI action actually complains that PAT is invalid - also, I think this secret was generated by @martenson back then - maybe it somehow got outdated?

AFAIK this is a GitHub personal access token? Or what kind of token is this?

**Comment by martenson** [comment]
The deploy step seems skipped due to failing tests or am I seeing it incorrectly?

**Comment by hechth** [comment]
> The deploy step seems skipped due to failing tests or am I seeing it incorrectly?

All tests are passing locally. Also the slash command dispatch stopped working saying `bad credentials`.

**Comment by bernt-matthias** [comment]
Then a new PAT is needed.

**Pull request closed without merging**
