### PR TITLE
RIAssigner 0.3.4

### LINKED ISSUE #320: RIAssigner v0.3.3

### PR DESCRIPTION
**Pull request by hechth**
Close #320.

### CODE REVIEW

**Comment by xtrojak** [comment]
I don't get it, why is this passing now, when this https://github.com/bioconda/bioconda-recipes/pull/39929 wasn't merged yet?

**Comment by xtrojak** [comment]
`numpy` version was pinned in https://github.com/bioconda/bioconda-recipes/pull/40182

**Comment by hechth** [comment]
@xtrojak so this passed the CI now?

**Comment by xtrojak** [comment]
> @xtrojak so this passed the CI now?

CI is passing, it also works fine locally, so should be good now.

**Pull request merged**
