### PR TITLE
update ramclustr to 1.2.2 and switch to conda dependencies

### LINKED ISSUE #114: update ramclustr to 1.2.1
And switch to use conda package as a requirement.

https://anaconda.org/bioconda/r-ramclustr

### PR DESCRIPTION
**Pull request by martenson**
getting the following on test
```
Error in round(ramclustObj$clri[i], 2) : 
  non-numeric argument to mathematical function
Calls: store_output -> <Anonymous> -> paste0
Execution halted
```

closes #114 

reported upstream at: https://github.com/cbroeckl/RAMClustR/issues/18

### CODE REVIEW

**Comment by martenson** [comment]
I adjusted this to fit the new merged ramclustr tool. The problem with the upstream lib persists.

**Comment by hechth** [comment]
> I adjusted this to fit the new merged ramclustr tool. The problem with the upstream lib persists.

Maybe it is time to try to contact the authors again via email?

**Comment by hechth** [comment]
@martenson Did you investigate the reasons for the test failure in the checks?

**Comment by martenson** [comment]
Yeah, I have WIP adjusting tests. It seems the test checks need to be updated since the version is sometimes included in metadta and some other minor things. I'll PR it tomorrow.

**Pull request merged**
