### PR TITLE
aplcms: provide values to cores=

### PR DESCRIPTION
**Pull request by ljocha**
Co-fixes https://github.com/RECETOX/apLCMS/issues/2

This is trivial but untested -- on Friday night I'm not capable of setting up my test environment, sorry. Kindly asking someone else to test on merge.

### CODE REVIEW

**Comment by martenson** [comment]
Should the default be `1` or rather unset? I feel like we should respect whatever aplcms is doing by default (not sure whether we changed that one though)

**Comment by martenson** [comment]
Identified: docker container is circumventing the Slurm limitations
fixed in: https://github.com/galaxyproject/galaxy/pull/10373

**Comment by ljocha** [comment]
Refering to galaxyproject/galaxy#10373 ... yes, if we manage to add the "--cpus NN" flag to "docker run" with NN taken from GALAXY_SLOTS, it's somewhat safer.

apLCMS calls R's parallel::detectCores() by default (well, I'm not sure whether it's Jirka's or original code), hence using all available cores (twice due to HT).

**Comment by martenson** [comment]
@ljocha iiuc the aplcms implementation is going to perform poorly because it will assume 24 cores but will be given only GALAXY_SLOTS worth of cores.

**Comment by ljocha** [comment]
Missed the last question -- yes, if apLCMS (or, better, the R's parallel library) guesses there are 24 cores available, it spawns 24 processes and the work is distributed among them. However, if docker limits the container to fewer cores only, the processes will start to compete, wasting time in switching context, kicking one another at least from L1 cache etc. Unless the code is extremely poorly written (not levaraging R matrix/vector operations), the impact on performance is serious.

**Comment by martenson** [comment]
Still something not quite correct.

```
Error in apLCMS::hybrid(files = c("/tmp/tmpatg82z5i/files/7/b/6/dataset_7b608363-30f1-4eae-a1af-3a0b622ca382.dat",  : 
  unused argument (cores = 1)
In addition: Warning messages:
1: In rgl.init(initValue, onlyNULL) : RGL: unable to open X11 display
2: 'rgl.init' failed, running with 'rgl.useNULL = TRUE'. 
Execution halted
```

**Comment by xtracko** [comment]
I superseded this with #48 cuz I did some incompatible changes to the apLCMS package. This should be closed in favor of #48.

**Comment by martenson** [comment]
@xtracko I just noticed the renames of `cores` to `cluster`.  Closing this as requested. Please reference and close the PR you are making obsolete next time.

**Pull request closed without merging**
